import './globals.css'
import NavBar from '@/components/navBar/navBar'
import Footer from '../components/footer/Footer'
import './fonts.css';

// import { Dosis, Concert_One, Balsamiq_Sans } from 'next/font/google'
 
// const dosis = Dosis({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-dosis',
// })

// const concert_one = Concert_One({
//   subsets: ['latin'],
//   weight: '400',
//   display: 'swap',
//   variable: '--font-concert-one',
// })

// const balsamiq_sans = Balsamiq_Sans({
//   subsets: ['latin'],
//   weight: '400',
//   display: 'swap',
//   variable: '--font-balsamiq-sans',
// })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body>
        <div className='layout'>
          <header className='header' >
            <NavBar />
          </header>
          <main className='main'>
            {children}
          </main>
          <footer className='footer'>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  )
}
